FROM node:22.18.0-bookworm-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ca-certificates git python3 build-essential \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV NODE_ENV=development TZ=America/Lima
EXPOSE 3000
# el comando real lo define docker-compose.dev.yml (npm ci + npm run dev)
CMD ["bash","-lc","npm run dev -- --host --port 3000"]
