version: "3.9"

services:
  emma_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: emma-astro-dev:alpine
    container_name: emma-dev
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      TZ: America/Lima
      # Base de datos en volumen local
      DATABASE_DIR: /data
      DATABASE_FILE: app.dev.db
      # Hot reload estable en contenedor
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./:/app:delegated               # tu código
      - node_modules_cache:/app/node_modules
      - ./data:/data                    # SQLite persistente en dev (similar a prod)
    command: >
      sh -lc "
        npm ci &&
        npm run dev -- --host --port 3000
      "
    restart: unless-stopped

volumes:
  node_modules_cache:
