version: '3.8'

services:
  # Aplicación EMMA
  emma-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: emma-app
    restart: unless-stopped
    ports:
      - "3000:4321"
    volumes:
      # Persistir base de datos SQLite
      - ./data:/app/data
      # Persistir uploads
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - emma-network

  # Nginx como reverse proxy
  nginx:
    image: nginx:alpine
    container_name: emma-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./public/uploads:/var/www/uploads:ro
    depends_on:
      - emma-app
    networks:
      - emma-network

  # Certbot para SSL automático (opcional)
  certbot:
    image: certbot/certbot
    container_name: emma-certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./public:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - emma-network

networks:
  emma-network:
    driver: bridge

volumes:
  emma-data:
    driver: local
