version: '3.8'

services:
  # Aplicaci칩n EMMA
  emma-app:
    build: 
      context: .
      dockerfile: docker/images/Dockerfile
    container_name: emma-app
    restart: unless-stopped
    ports:
      - "3000:4321"
    volumes:
      # Persistir base de datos SQLite - mapear directamente el archivo
      - ./database.sqlite:/app/database.sqlite
      # Persistir uploads
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
      # Variables de entorno para configuraci칩n de admin
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@emma.pe}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      - DOMAIN=${DOMAIN:-descubre.emma.pe}
      # Configuraci칩n de uploads
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES:-pdf,doc,docx}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - emma-network

  # Nginx como reverse proxy
  nginx:
    image: nginx:alpine
    container_name: emma-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./public/uploads:/var/www/uploads:ro
    depends_on:
      - emma-app
    networks:
      - emma-network

  # Certbot para SSL autom치tico (opcional)
  certbot:
    image: certbot/certbot
    container_name: emma-certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./public:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - emma-network

networks:
  emma-network:
    driver: bridge

volumes:
  emma-data:
    driver: local
